name: piranha2
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python==3.12
  - bcftools=1.20
  - coreutils>=9.1
  - flopp=0.2.0
  - freebayes=1.3.6
  - iqtree>=2.1
  - cov-ert::jclusterfunk>=0.0.25
  - mafft
  - minimap2>=2.17
  - rasusa=0.7.1
  - samtools>=1.20
  - snakemake-minimal>=9.9.0
  - medaka
