name: piranha
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - bcftools=1.11
  - coreutils=9.1
  - flopp=0.2.0
  - freebayes=1.3.6
  - iqtree>=2.1
  - cov-ert::jclusterfunk>=0.0.25
  - mafft
  - minimap2=2.17
  - pyabpoa
  - rasusa=0.7.1
  - samtools=1.11
  - snakemake-minimal
  - tabix=1.11
