[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "piranha"
dynamic = ["version"]
dependencies = [
    "mako==1.2",
    "pandas~=1.5",
    "snipit>=1.2",
    "biopython",
    "medaka",
    "numpy~=1.26.4",
    "scipy~=1.11"
]
requires-python = ">=3.10"
authors = [
  { name="Aine OToole", email="aine.otoole@ed.ac.uk"},
]
description = "Poliovirus Investigation Resource Automating Nanopore Haplotype Analysis"
readme = "README.md"

classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

license = "GPL-3.0-or-later"
license-files = ["LICEN[CS]E*"]

[project.urls]
Homepage = "https://github.com/aineniamh/piranha"
Issues = "https://github.com/aineniamh/piranha/issues"

[project.scripts]
squirrel-cli = "squirrel.command:main"

[tool.setuptools.dynamic]
version = {attr = "piranha.__version__"}

